### ISSUE TITLE
suno new Framework criando estrutura errada

### ISSUE THREAD

**Issue by pedroams** [concretesolutions/sunomono#23]
Ao criar um projeto com o comando suno new Appium (primeira letra maiúscula) a sunomono cria uma estrutura com uma pasta chamada Users. 

![image](https://user-images.githubusercontent.com/35699650/37227834-509e95d8-23bd-11e8-8296-457fb81eb8f5.png)

![image](https://user-images.githubusercontent.com/35699650/37227865-6ab219d6-23bd-11e8-9bfa-6b2a465f1e0e.png)

![image](https://user-images.githubusercontent.com/35699650/37227933-a2625dbe-23bd-11e8-9b7e-12ce5560d669.png)

**Comment by cs-wellington-santos** [comment]
@pedroams valeu, vou dar uma olhada já

**Comment by cs-wellington-santos** [comment]
@pedroams sunomono 1.0.6 foi disponibilizada :)
