### ISSUE TITLE
Problema de encoding ao gerar feature/projeto utillizando --lang=pt

### ISSUE THREAD

**Issue by cebindani** [concretesolutions/sunomono#6]
Olá!
Verifiquei que no no Windows (10, 64bits), ao gerar o projeto e a feature utilizando o argumento `--lang=pt`, as palavras reservadas **Então**, **Cenário** estão com problemas de encoding, gerando erros ao executar as features.

> cs-bdd new especificacao --lang=pt
> cs-bdd g feature consultar --lang=pt

![captura de tela 4](https://cloud.githubusercontent.com/assets/1211879/17034819/b2e6f4a8-4f5a-11e6-8daa-bee6b712447c.png)

![base_steps 2](https://cloud.githubusercontent.com/assets/1211879/17034910/16f80d9c-4f5b-11e6-9899-6d1002d24e19.png)

**Comment by cs-wellington-santos** [comment]
Muito obrigado por nos notificar @cebindani, vamos olhar o que pode estar acontecendo.

**Comment by samycici** [comment]
Oi @cebindani esse problema ocorre porque o Win não usa o encoding UTF8 como default. Para resolver, execute no terminal:

 [HKEY_CURRENT_USER\Software\Microsoft\Command Processor] "AutoRun"="chcp 65001"

que muda o enconding pra UTF8. 
Assim você consegue usar a gem com o parâmetro de português sem problemas :)

**Comment by cebindani** [comment]
Agora deu certo!!! :smile: 
Agradeço muito pela atenção @samycici e @cs-wellington-santos !!

**Comment by wellavelino** [comment]
De nada :)
